---
packages_to_install:
  - git
  - fish
  - neovim
  - kitty
  - tmux
  - tmuxp
  - htop
  - curl
  - make
  - stow
  - ranger
  - starship
  - speedtest-cli
  - neofetch
  - ansible-lint

  # Manage fonts
  - fontconfig
  - unzip
