---
packages_to_install:
  - git
  - fish
  - neovim
  - kitty
  - tmux
  - tmuxp
  - htop
  - curl
  - make
  - stow
  - ranger
  - starship
  - speedtest-cli
  - neofetch
  - ansible-lint
  - ripgrep
  - fd
  - zoxide
  - fzf
  - yadm

  # Manage fonts
  - fontconfig
  - unzip

packages_aur:
  - treq-bin
  - lazydocker
