---
- name: Install essential packages of Pacman
  become: true
  pacman:
    name: "{{ pacman_packages }}"
    state: present

- name: Install yay to use AUR packages
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present

# - name: Install essential packages of AUR
#   kewlfft.aur.aur:
#     name: "{{ item }}"
#     use: yay
#     state: present
#   loop: "{{ packages_aur }}"

# - name: Install NvChad
#   block:
#     - name: Check if Neovim already has a config file (init.lua)
#       stat:
#         path: /home/{{ ansible_user_id }}/.config/nvim/init.lua
#       register: some_neovim_config_installed

#     - name: Print files Neovim init.lua
#       debug:
#         msg: "Status NEOVIM configuration: {{ some_neovim_config_installed }}, {{ some_neovim_config_installed.stat }}"

#     - name: Install NvChad configs
#       command: git clone https://github.com/NvChad/NvChad /home/{{ ansible_user_id }}/.config/nvim --depth 1
#       when: some_neovim_config_installed.stat.exists == False

#     - name: Create folder to custom NvChad configs
#       command: mkdir -p /home/{{ ansible_user_id }}/.config/nvim/lua/custom
#       when: some_neovim_config_installed.stat.exists == False

# - name: Setup dotfiles
#   block:
#     - name: Check if dotfiles repository is installed
#       command: yadm status
#       register: has_yadm_repo
#       ignore_errors: true

#     - name: Clone dotfiles repository
#       command: yadm clone git@github.com:talis-fb/dotfiles-yadm.git
#       when: has_yadm_repo is failed

#     - name: Bootstrap Yadm
#       command: yadm bootstrap

# - name: Setup Tmux Plugin Manager - tpm
#   git:
#     repo: https://github.com/tmux-plugins/tpm.git
#     dest: /home/{{ ansible_user_id }}/.tmux/plugins/tpm
#     clone: true
#     update: true

# - name: Set user shell to fish
#   become: true
#   user:
#     name: "{{ ansible_user_id }}"
#     shell: /bin/fish
#     generate_ssh_key: true

# - name: Install Hack Nerd Fonts
#   block:
#     - name: ensure fonts directory
#       file:
#         path: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
#         state: directory

#     - name: Hack Font exists
#       shell: "ls {{ lookup('env', 'HOME') }}/.local/share/fonts/Hack*Nerd*Font*Complete*"
#       register: hack_exists
#       ignore_errors: true

#     - name: Download Hack
#       when: hack_exists is failed
#       unarchive:
#         src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
#         dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/"
#         remote_src: true

# - name: Setup Fisher
#   block:
#     - name: ensure fisher is not installed
#       stat:
#         path: /home/{{ ansible_user_id }}/.config/fish/functions/fisher.fish
#       register: fisher_file

#     - name: Install fisher (fish plugin manager)
#       command: curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
#       when: fisher_file.stat.exists == False

#     - name: Install fzf fish plugin
#       command: fisher install PatrickF1/fzf.fish
#       when: fisher_file.stat.exists == False


