---
- name: Init the magic...
  hosts: localhost
  connection: local

  # vars_prompt:
  #   - name: usuario
  #     prompt: Qual o nome do seu usuario?
  #     private: false

    # - name: mvp_folder
    #   prompt: Onde armazenar o diretorio pro Wisefi? (caminho absoluto)
    #   private: false

  roles:
    - pacman
    - dev
    - desktop_apps
    - docker
    # - gnome
    # - wisefi
    # - ableton.nix
