---
- name: Init the magic...
  hosts: localhost
  connection: local

  # vars_prompt:
  #   - name: usuario
  #     prompt: What is your username?
  #     private: false

  roles:
    - pacman
    - dev
    - desktop_apps
    - docker
