---
- name: Init the magic...

  # Setup to only target the machine executing it
  hosts: localhost
  connection: local

  roles:
    - system/home_dir_structure
    - system/timezone
    - system/pacman
    - system/shell
    - system/nerdfonts
    - system/btrfs
    - system/bluetooth
    - docker

    - pacman_apps
    - qemu

    - flatpak_apps

    # Need authentication first
    # - work/inmaster
