---
- name: Backup pacman.conf
  become: true
  copy:
    src: /etc/pacman.conf
    dest: /etc/pacman.conf.backup
      
- name: Pacman options - ParallelDownloads
  become: true
  lineinfile:
    path: /etc/pacman.conf
    regexp: ^#?ParallelDownloads =
    line: ParallelDownloads = 7

- name: Pacman options - Color
  become: true
  lineinfile:
    path: /etc/pacman.conf
    regexp: ^#?Color$
    line: Color

# - name: Enable ILoveCandy option
#   become: true
#   lineinfile:
#     dest: /etc/pacman.conf
#     regexp: '^#?ILoveCandy'
#     line: 'ILoveCandy'

- name: Pacman -Syu
  become: true
  pacman:
    update_cache: true
    upgrade: true

- name: Install yay to use AUR packagesvim
  become: true
  become_user: "{{ username }}"
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present