---
- name: Setup bluetooth
  block:
    - name: Install bluetooth packages
      become: true
      pacman:
        name: "{{ item }}"
        state: present
      loop: 
        - bluez
        - bluez-utils
        - blueman


    - name: Enable fast connectable bluetooth
      become: true
      lineinfile:
        path: /etc/bluetooth/main.conf
        regexp: '#?FastConnectable ='
        line: 'FastConnectable = true'

    - name: Enable bluetooth
      become: true
      service:
        name: bluetooth
        enabled: yes
  notify: Restart bluetooth
