---
- name: Setup bluetooth
  block:
    - name: Install bluetooth packages
      become: true
      pacman:
        name:
          - bluez
          - bluez-utils
          - blueman
        state: present

    - name: Enable fast connectable bluetooth
      become: true
      lineinfile:
        path: /etc/bluetooth/main.conf
        regexp: '#?FastConnectable ='
        line: 'FastConnectable = true'

    - name: Enable bluetooth
      become: true
      service:
        name: bluetooth
        enabled: yes
  notify: Restart bluetooth
