---
- name: Install development packages
  become: true
  pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: Start docker service in Systemd
  become: true
  service:
    name: docker
    state: started

- name: Enable docker service in Systemd
  become: true
  service:
    name: docker
    enabled: true

- name: Put User to docker group
  become: true
  user:
    name: "{{ username }}"
    groups:
      - wheel
      - docker
    append: true
