---
- name: Install essential packages of Pacman
  become: true
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - ttf-hack-nerd
    - ttf-nerd-fonts-symbols
    - ttf-iosevka-nerd
    - ttf-jetbrains-mono-nerd